#!/bin/sh

WG_QUICK=""

function cmd_exists() {
  if type "$1" &> /dev/null; then
    return 0
  else
    return 1
  fi
}

if cmd_exists wg-quick; then
  WG_QUICK="wg-quick"
elif cmd_exists nix-build; then
  if nix-build "<nixpkgs>" -A wireguard-tools -o /tmp/wg; then
    WG_QUICK="/tmp/wg/bin/wg-quick"
  elif nix build nixpkgs#wireguard-tools -o /tmp/wg; then
    WG_QUICK="/tmp/wg/bin/wg-quick"
  else
    echo "nix install failed" >&2
    exit 2
  fi
elif cmd_exists apt-get; then
  sudo apt-get update
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends wireguard-tools
  WG_QUICK="wg-quick"
fi

if [ ! -v JIT6_TOKEN ]; then
  echo "No jit6 token provided, aborting." >&2
  exit 2
fi

wget "https://${JIT6_TOKEN}@jit6.mkg20001.io/jit6.php" -O /tmp/jit6.conf
sudo "$WG_QUICK" up /tmp/jit6.conf
